### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by vitordevsp** [MariBecker/jm-viagens#1]
Olá Mari, estava olhando seus repositórios, e gostaria de fazer uma sugestão, da para hospedar esses sites estáticos com o GitHub Pages, assim fica muito mais fácil de visualizar o resultado final do site, nem precisar clonar e rodar o projeto localmente.

**Comment by MariBecker** [comment]
Olá! Esse foi um dos primeiros projetos que eu fiz, então não sabia muito bem como funcionava por aqui. Obrigada por me lembrar, vou arrumar esse!
